name: volt
description: 'A utility library with detailed pretty printing!'
version: 0.0.1
repository: https://github.com/intfract/dart
homepage: https://github.com/intfract

dev_dependencies: {}
environment:
  sdk: '>=2.10.0 <3.0.0'
